# Generated by Django 5.2.5 on 2025-10-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('speaker', 'Speaker'), ('graduate', 'Graduate'), ('student', 'Student'), ('faculty', 'Faculty'), ('participant', 'Participant'), ('guest', 'Guest'), ('volunteer', 'Volunteer')], default='participant', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
